config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create] do
    member do
      get :ikitais
    end
  end
  resources :posts
  resources :favorites, only: [:create, :destroy]
  #------------12/25-------------------
  #get 'posts/eat', to: 'posts#eat'
  #get 'posts/stay', to: 'posts#stay'
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :posts
  has_many :favorites                                    #行きたいねをしている投稿への参照
  has_many :ikitais, through: :favorites, source: :post  #行きたいねをしている投稿(複数）favoritesテーブルのpost_id参照
  
  def ikitaine(mark_post)
    self.favorites.find_or_create_by(post_id: mark_post.id)
  end
  
  def unikitaine(mark_post)
    favorite = self.favorites.find_by(post_id: mark_post.id)
    favorite.destroy if favorite
  end
  
  def ikitai?(mark_post)
    self.ikitais.include?(mark_post)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [ :show]
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(id: :desc).page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def ikitais
    @user = User.find(params[:id])
    @ikitais = @user.ikitais.order(id: :desc).page(params[:page])
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/views/users/_users_posts.html.erb
<div class="container">
  <ul class="list-unstyled">
    <% posts.each do |post| %>
      <li class="media mb-3 pb-3 border-bottom">
        <div class="media-body">
          <div class="row">
            <div class="col-6">
              <div>
                <%= link_to post.title, post_path(post) %>
                <span class="text-muted"><%= post.area %><%= post.created_at %></span>
                <span class="badge badge-warning">行きたいね <%= post.favorites.count %> 件</span>
              </div>
              <% if post.image? %>
                <%= image_tag post.image.url, width: "250", alt: "post image" %>
              <% end %>
              <div><%= post.subtitle %></div>
              <%#<div>投稿者<%= post.user.name %><%#</div> %>
            </div>
            <div class="col-6">
              <div><%= post.content %></div>
            </div>
          </div>
        </div>
         
        <%# --------ログイン中のみ可-------%>
        <% if logged_in? %>
          <%# --------行きたいねボタン-------%>
          <%= render 'favorites/favorite_button', post: post %>
          
          <%# ----------投稿者のみ編集/削除可 ------------%>
          <% if current_user == post.user %>
            <%= link_to edit_post_path(post), class: 'btn btn-success btn-sm'  do %>
              <i class="fas fa-edit"></i>
            <% end %>
            <%= link_to post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          <% end %>
        <% end %>
      </li>
    <% end %>
    <%#= paginate posts %>
  </ul>
</div>

app/views/users/ikitais.html.erb
<ul class="nav nav-tabs nav-justified mb-3 nav-pills">
  <li class="nav-item">
    <a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿記事一覧<span class="badge badge-secondary"></span></a>
  </li>
  <li class="nav-item">
    <a href="<%= ikitais_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(ikitais_user_path(@user)) %>">💛行きたいね<span class="badge badge-secondary"></span></a>
  </li>
</ul>

<%# -----行きたいね一覧 ----- %>
<div id="ikitai-list" class="tab-pane active">
  <% if @ikitais.any? %>
    <%= render 'users_posts', posts: @ikitais %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <div class="card" >
      <div class="card-header bg-warning">
        ユーザ登録
      </div>
      <div class="card-body">
        <%= form_with(model: @user, local: true) do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
      
          <div class="form-group">
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認用）' %>
            <%= f.password_field :password_confirmation, class: 'form-control mb-4' %>
          </div>

          <%= f.submit '登　　録', class: 'btn btn-warning btn-block' %>
        <% end %>
      </div>
    </div>  
  </div>
</div>

app/views/users/show.html.erb
<%#<div class="col-sm-12">
  <ul class="nav nav-tabs nav-justified mb-3 nav-pills">
    <li class="nav-item">
      <a href="#posts-list" class="nav-link active" data-toggle="tab">投稿記事一覧</a>
    </li>
    <li class="nav-item">
      <a href="#ikitai-list" class="nav-link" data-toggle="tab">行きたいね</a>  
    </li>
  </ul>
</div>%>

<ul class="nav nav-tabs nav-justified mb-3 nav-pills">
  <li class="nav-item">
    <a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿記事一覧<span class="badge badge-secondary"></span></a>
  </li>
  <li class="nav-item">
    <a href="<%= ikitais_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(ikitais_user_path(@user)) %>">💛行きたいね<span class="badge badge-secondary"></span></a>
  </li>
</ul>

<div class="tab-content">
  <div id="posts-list" class="tab-pane active">
    <% if @posts.any? %>
      <%= render 'users_posts', posts: @posts %>
    <% end %>
  </div>
</div>