config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create] do
    member do
      get :ikitais
    end
  end
  resources :posts
  resources :favorites, only: [:create, :destroy]
  #------------12/25-------------------
  #get 'posts/eat', to: 'posts#eat'
  #get 'posts/stay', to: 'posts#stay'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  mount_uploader :image, GimageUploader
  
  has_many :favorites,dependent: :destroy     #行きたいねをしているユーザへの参照
  has_many :users, through: :favorites        #行きたいねをしているユーザ(複数）favoritesのuser_id参照
  
  validates :title, presence: true, length: { maximum: 50 }
  validates :area, length: { maximum: 50 }
  validates :subtitle, length: { maximum: 100 }
  validates :content, presence: true, length: { maximum: 255 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in, only: [ :new, :edit, :create, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:destroy]

  # GET /posts
  # GET /posts.json
  def index
    @user = current_user
    @categories = [
      [0, "見る／遊ぶ"],
      [1, "食べる"],
      [2, "泊まる"]
    ]
    @posts = Post.order(id: :desc).page(params[:page]).per(10)
    #@plays = Post.where(category: "0")   #見る／遊ぶ
    #@posts = Post.where(category: "0")   #見る／遊ぶ
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find_by(id: params[:id])
      
  end

  # GET /posts/new
  def new
    @post = Post.new
    @toukou = '新規投稿'
  end

  # GET /posts/1/edit
  def edit
    @toukou = '投稿記事編集'
  end

  # POST /posts
  # POST /posts.json
  def create
    if logged_in?
      @post = current_user.posts.build(post_params) # form_with用
      @posts = current_user.posts.order(id: :desc).page(params[:page]).per(10)
    
      #@post = Post.new(post_params)
      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  #def eat   #食べる投稿一覧
    #@user = current_user
    #@eats = Post.where(category: "1")
    #@posts = Post.where(category: "1") 
  #end
  
  #def stay  #泊まる投稿一覧
    #@user = current_user
    #@stays = Post.where(category: "2")
    #@posts = Post.where(category: "2") 
  #end

  private
  
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:category, :title, :subtitle, :area, :content, :image, :user_id)
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end

app/views/posts/0108****_posts.html.erb
<%# ログインしていなくても投稿一覧表示可 %>
<%# if Post.where(category: category[0]).any? %>
  <div class="container">
    <ul class="list-unstyled">
      <% Post.where(category: @category).each do |post| %>
        <li class="media mt-3 pb-3 border-bottom">
          <div class="media-body">
            <div class="row">
              <div class="col-6">
                <div>
                  <%= link_to post.title, post_path(post) %>
                  <span class="text-muted"><%= post.area %><%= post.created_at %></span>
                  <span class="badge badge-warning">行きたいね <%= post.favorites.count %> 件</span>
                </div>
                <% if post.image? %>
                  <%= image_tag post.image.url, width: "250", alt: "post image" %>
                <% end %>
                <%#= post.user %>
                <div><%= post.subtitle %></div>
              </div>
              <div class="col-6">
                <div><%= post.content %></div>
              </div>
            </div>
          </div>
         
          <%# --------ログイン中のみ可-------%>
          <% if logged_in? %>
            <%# --------行きたいねボタン-------%>
            <%= render 'favorites/favorite_button', post: post %>
          
          <%# ----------投稿者のみ編集/削除可 ------------%>
            <% if current_user == post.user %>
              <%= link_to edit_post_path(post), class: 'btn btn-success btn-sm' do %>
                <i class="fas fa-edit"></i>
              <% end %>
              <%= link_to post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
          <% end %>
        </li>
      <% end %>
      <%#= paginate posts %>
    </ul>
  </div>
<%# end %>

app/views/posts/0108****index.html.erb
<%#---------------- メイン画像表示 ------------------%>
<div class="jumbotron" style="background:url(/IMG_0003.JPG); background-size:cover;">
  <div class="container-fluid">
    <h1 style="color: #ffffff;">やまぐちの行きたいねを見つけよう!!</h1>
    <%# <p class="text-white">サブタイトル</p> %>
    <%#---------------- 検索フォーム追加 -----------------%>
    <div class="search-form mt-4 text-center">
      <%= form_with url: search_path, method: :get, local: true do |f| %>
        <%= f.text_field :keyword, value: @keyword %>
        <%= f.submit "検索", class: 'btn btn-warning' %>
      <% end %>
    </div>
  </div>
</div>

<%#---------------- カテゴリー別タブ表示 --------------%>
<div class="col-sm-12">
  <ul class="nav nav-tabs nav-justified mb-3 nav-pills">
    <li class="nav-item">
      <a href="<%= 'posts' %>" class="nav-link <%= 'active' if current_page?('posts') %>" data-toggle="tab"><%= '見る／遊ぶ' %></a>
    </li>
    <li class="nav-item">
      <a href="<%=posts_eat_path(@posts) %>" class="nav-link <%#= 'active' if current_page?(posts_eat_path(@posts))) %>" data-toggle="tab"><%= '食べる' %></a>
    </li>
    <li class="nav-item">
      <a href="<%=posts_stay_path(@posts) %>" class="nav-link <%#= 'active' if current_page?(posts_stay_path(@posts)) %>" data-toggle="tab"><%= '泊まる' %></a>
    </li>
  </ul>
</div>
<%#---------------- 投稿記事一覧表示 ------------------%>
<div class="tab-content">
  <div id="category_0" class="tab-pane active" >
    <% if Post.where(category: "0").any? %>
      <%#= render 'posts', category: category %>
      <% @category = "0" %>
      <%= render 'posts', category: @posts %>
    <% end %>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <div class="col-sm-10 mx-auto">
      <div class="card" >
        <div class="card-header bg-success">
          <%= @toukou %>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="form-group col-sm-3">
              <%= form.label :category, 'カテゴリを選ぶ' %>
              <%= form.select :category, {'見る／遊ぶ':0,'食べる':1,'泊まる':2},{ include_blank: "選択して下さい"},{ class: 'form-control' , required: true } %>
            </div>
          </div>
            
          <div class="form-group">
            <%= form.label :title, 'タイトルを入力' %>
            <%= form.text_field :title, { class: 'form-control', required: true } %>  <%# required: trueで空の送信を防ぐ %>
          </div>
          
          <div class="row">
　          <div class="form-group">
              <%= form.label :area, 'エリアを入力' %>
              <%= form.text_field :area, { class: 'form-control' } %>
            </div>

            <div class="form-group col-sm-8">
              <%= form.label :subtitle, 'サブタイトルを入力' %>
              <%= form.text_field :subtitle, { class: 'form-control' } %>
            </div>
          </div>

          <div class="form-group">
            <%= form.label :content, '詳細情報を入力（概要、おすすめ内容など）' %>
            <%= form.text_area :content, { class: 'form-control', required: true } %>
          </div>
            
          <div class="form-group clo-sm-6">
            <%= form.label :image, 'フォト' %>
            <%= form.file_field :image %>
          </div>

          <div class="actions">
            <%= form.submit '投稿する', class: 'btn btn-success btn-block' %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<%# ログインしていなくても投稿一覧表示可 %>
<%# if Post.where(category: category[0]).any? %>
  <div class="container">
    <ul class="list-unstyled">
      <% Post.where(category: category[0]).each do |post| %>
        <li class="media mt-3 pb-3 border-bottom">
          <div class="media-body">
            <div class="row">
              <div class="col-6">
                <div>
                  <%= link_to post.title, post_path(post) %>
                  <span class="text-muted"><%= post.area %><%= post.created_at %></span>
                  <span class="badge badge-warning">行きたいね <%= post.favorites.count %> 件</span>
                </div>
                <% if post.image? %>
                  <%= image_tag post.image.url, width: "250", alt: "post image" %>
                <% end %>
                <%#= post.user %>
                <div><%= post.subtitle %></div>
              </div>
              <div class="col-6">
                <div><%= post.content %></div>
              </div>
            </div>
          </div>
         
          <%# --------ログイン中のみ可-------%>
          <% if logged_in? %>
            <%# --------行きたいねボタン-------%>
            <%= render 'favorites/favorite_button', post: post %>
          
          <%# ----------投稿者のみ編集/削除可 ------------%>
            <% if current_user == post.user %>
              <%= link_to edit_post_path(post), class: 'btn btn-success btn-sm' do %>
                <i class="fas fa-edit"></i>
              <% end %>
              <%= link_to post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
          <% end %>
        </li>
      <% end %>
      <%#= paginate posts %>
    </ul>
  </div>
<%# end %>

app/views/posts/_search_posts.html.erb
<%# ログインしていなくても投稿一覧表示可 %>
<%# if Post.where(category: category[0]).any? %>
  <div class="container">
    <ul class="list-unstyled">
      <% @posts.where(category: category[0]).each do |post| %>
        <li class="media mt-3 pb-3 border-bottom">
          <div class="media-body">
            <div class="row">
              <div class="col-6">
                <div>
                  <%= link_to post.title, post_path(post) %>
                  <span class="text-muted"><%= post.area %><%= post.created_at %></span>
                  <span class="badge badge-warning">行きたいね <%= post.favorites.count %> 件</span>
                </div>
                <% if post.image? %>
                  <%= image_tag post.image.url, width: "250", alt: "post image" %>
                <% end %>
                <%#= post.user %>
                <div><%= post.subtitle %></div>
              </div>
              <div class="col-6">
                <div><%= post.content %></div>
              </div>
            </div>
          </div>
         
          <%# --------ログイン中のみ可-------%>
          <% if logged_in? %>
            <%# --------行きたいねボタン-------%>
            <%= render 'favorites/favorite_button', post: post %>
          
          <%# ----------投稿者のみ編集/削除可 ------------%>
            <% if current_user == post.user %>
              <%= link_to edit_post_path(post), class: 'btn btn-success btn-sm' do %>
                <i class="fas fa-edit"></i>
              <% end %>
              <%= link_to post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
          <% end %>
        </li>
      <% end %>
      <%#= paginate posts %>
    </ul>
  </div>
<%# end %>

app/views/posts/eat.html.erb
<%= "eat!!" %>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

<%= link_to '編集前に戻る', @post %>
<%#= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%#---------------- メイン画像表示 ------------------%>
<div class="jumbotron" style="background:url(/IMG_0003.JPG); background-size:cover;">
  <div class="container-fluid">
    <h1 style="color: #ffffff;">やまぐちの行きたいねを見つけよう!!</h1>
    <%# <p class="text-white">サブタイトル</p> %>
  </div>
</div>

<%#---------------- カテゴリー別タブ表示 --------------%>
<div class="col-sm-12">
  <ul class="nav nav-tabs nav-justified mb-3 nav-pills">
    <% @categories.each do |category| %>
      <li class="nav-item">
        <% if category[0] == 0 %>
          <a href="#category_<%= category[0]%>" class="nav-link active" data-toggle="tab"><%= category[1] %></a>
        <% else %>
          <a href="#category_<%= category[0]%>" class="nav-link" data-toggle="tab"><%= category[1] %></a>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>
<%#---------------- 投稿記事一覧表示 ------------------%>
<div class="tab-content">
  <% @categories.each do |category| %>
    <% if category[0] == 0 %>
      <div id="category_<%= category[0]%>" class="tab-pane active" >
        <% if Post.where(category: category[0]).any? %>
          <%= render 'posts', category: category %>
        <% end %>
      </div>
    <% else %>
      <div id="category_<%= category[0]%>" class="tab-pane" >
        <% if Post.where(category: category[0]).any? %>
          <%= render 'posts', category: category %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/posts/new.html.erb
<% if logged_in? %>
  <%= render 'form', post: @post %>
<% end %>

app/views/posts/search.html.erb
<%#---------------- メイン画像表示 ------------------%>
<div class="jumbotron" style="background:url(/IMG_0003.JPG); background-size:cover;">
  <div class="container-fluid">
    <h1 style="color: #ffffff;">やまぐちの行きたいねを見つけよう!!</h1>
    <%# <p class="text-white">サブタイトル</p> %>
    <%#---------------- 検索フォーム追加 -----------------%>
    <div class="search-form mt-4 text-center">
      <%= form_with url: search_path, method: :get, local: true do |f| %>
        <%= f.text_field :keyword, value: @keyword %>
        <%= f.submit "検索", class: 'btn btn-warning' %>
      <% end %>
    </div>
  </div>
</div>
<%#---------------- カテゴリー別タブ表示 --------------%>
<div class="col-sm-12">
  <ul class="nav nav-tabs nav-justified mb-3 nav-pills">
    <% @categories.each do |category| %>
      <li class="nav-item">
        <% if category[0] == 0 %>
          <a href="#category_<%= category[0]%>" class="nav-link active" data-toggle="tab"><%= category[1] %></a>
        <% else %>
          <a href="#category_<%= category[0]%>" class="nav-link" data-toggle="tab"><%= category[1] %></a>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<%#---------------- 投稿記事一覧表示 ------------------%>
<div class="tab-content">
  <% @categories.each do |category| %>
    <% if category[0] == 0 %>
      <div id="category_<%= category[0]%>" class="tab-pane active" >
        <% if @posts.where(category: category).any? %>
          <%= render 'search_posts', category: category %>
        <% end %>
      </div>
    <% else %>
      <div id="category_<%= category[0]%>" class="tab-pane" >
        <% if @posts.where(category: category).any? %>
          <%= render 'search_posts', category: category %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">

      <p><%= @post.title %></p>

      <% if @post.image? %>
        <%= image_tag @post.image.url, id: "pic", size: "480x320", alt: "post image" %>
      <% end %>

      <P>
        <span class="badge badge-warning">投稿者</span><%= @post.user.name %> 
        <span class="badge badge-warning">エリア</span><%= @post.area %> 
        <span class="badge badge-warning">投稿日</span><%= @post.created_at %>
      </P>
      
      <p><span class="badge badge-warning">ポイント</span><%= @post.subtitle %></p>
    </div>
    
    <div class="col-md-6">
      <div class="row" >
        <div class="col-md-4">     
          <% if logged_in? %>
            <div class="row">
              <%= render 'favorites/favorite_button', post: @post %>
              <span class="badge badge-warning mt-2 mb-2">行きたいね <%= @post.favorites.count %> 件</span>
            </div>
          <% end %>
        </div>
        
        <div class="offset-md-4 col-md-4">
          <% if logged_in? %>
            <% if current_user == @post.user %>
              <%= link_to edit_post_path(@post), class: 'btn btn-success btn-sm'  do %>
                <i class="fas fa-edit"></i>
              <% end %>
              <%= link_to @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
        
      <span class="badge badge-success">投稿内容</span>
      <p><%= @post.content %></p>
    </div>
  </div>
</div>

<%= link_to :back do %>
  <button class="badge badge-success">戻る</button>
<% end %>